/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package classes

class Aluno(val nome: String, val email: String) {
    fun qualTurma() : Int {
        return when {
            nome.length > 10 -> 10
            else -> 9
        }
    }
}

// O qual seria a diferença entre data class?
  // Kotlin tem "data class" que são particularmente úteis para armazenar dados.
// As classes de dados têm a mesma funcionalidade que as classes,
// mas vêm automaticamente com funções de membro adicionais.
// Estas funções membro permitem-lhe imprimir facilmente a instância para uma saída legível,
// comparar instâncias de uma classe, copiar instâncias, e muito mais.
// Uma vez que estas funções estão automaticamente disponíveis, não tem de perder tempo a escrever o mesmo código padrão para cada uma das suas classes.

fun main() {
    val alunoA = Aluno("Marcus", "lowpoc.developer@gmail.com")
    val alunoB = Aluno("Marcus", "lowpoc.developer@gmail.com")
    
    println(alunoA.nome)
    println(alunoA.qualTurma())
    
    println(alunoA == alunoB)
    println(alunoA)
    
    println("#############################Sua vez de codar!###############################")
    
    // Tarefa 1: Adicione nova propriedade idade que seja  mutável na classe aluno
    // Tarefa 2: Altere o metodo qualTurma para ao invés de usar o tamanho do nome , use a idade.
    // Tarefa 3: alterar a classe aluno para que conseguimos comparar objetos de forma mais simplificida , sem necessidade de usar boirplate.
}